### ISSUE TITLE
Add monitoring with check_rancher2

### ISSUE THREAD

**Issue by Napsty** [jmreicha/awesome-rancher#16]
Great idea to put some helpful links together.
I recently started a monitoring plugin called "check_rancher2" to check the Rancher2 environments using the Rancher 2 API. Would be cool if you could add it to the list, too.
https://github.com/Napsty/check_rancher2

**Comment by jmreicha** [comment]
Sure, I can add it.  It looks like link in the repo is broken?

**Comment by Napsty** [comment]
Nope, link is correct. Was Github down? ;)

**Comment by Napsty** [comment]
Or do you mean the link to documentation?  Yes, it's not finished and published yet. It's currently in work.

**Comment by jmreicha** [comment]
https://www.claudiokuenzler.com/monitoring-plugins/check_rancher2.php gives me a 404.

**Comment by jmreicha** [comment]
As long as you knew about it already then it doesn't bother me.  I added your repo to the list.  Feel free to open another issue if you want another project added.
